### ISSUE TITLE
Bug: Incorrect linting for job variables

### ISSUE THREAD

**Issue by kehralexander** [fiskirton/GitLabCI-plugin#14]
### Description:
When defining variables for a job the hints given by plugin are wrong.  
Relevant gitlab docs: https://docs.gitlab.com/ee/ci/yaml/#variables  

### Expected behaviour:  
Everything schould be OK  

### Actual behaviour:
this should work:
![image](https://user-images.githubusercontent.com/11942295/177144734-f71c474e-2b0f-4217-b72a-86b2f6fe1d14.png)
this is invalid by gitlab spec but hinted on by plugin, also does not "work":
![image](https://user-images.githubusercontent.com/11942295/177144922-535de384-3565-456c-a75f-6fed2f594f55.png)

### Attachments
code used in screenshots
```yml
package_rpm:
    stage: package
    only:
      - tagged
    variables:
        PACKAGE_NAME:
            value: "some_var_name"
            description: ""
    script:
        - mkdir build && cd build
```
```yml
package_rpm:
    stage: package
    only:
      - tagged
    variables:
        PACKAGE_NAME:  "some_var_name"
    script:
        - mkdir build && cd build
```
### Versions
| Name  | Version  |
| ----------------------- | ------- |
| fiskirton GitLabCI | 0.0.3 |
| Intellij IDEA | 2022.1.3 |
